theme: minima
title: My first site on Git hub
author: Kenzhe Estaev 
email: kenje.estaev1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The purpose of this site is to demonstrate the ability of Kenzhe to work with git hub and 
  create a content.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
